name: "[master] Release"

on:
  push:
    paths-ignore:
      - "**/*.md"
      - ".vscode/**"

jobs:
  Build:
    uses: ./.github/workflows/build.yml

  Release:
    name: Release latest on GitHub
    needs: Build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Download All Artifacts
        uses: actions/download-artifact@v8
        with:
          name: luna-artifacts
          path: ./dist/

      - name: Publish latest release on GitHub
        uses: softprops/action-gh-release@v3
        with:
          token: ${{ github.token }}
          tag_name: latest
          name: Latest Release
          prerelease: false
          make_latest: "true"
          files: ./dist/**